openapi: 3.0.0
info:
  title: "Safe Wrapper REST API Documentation"
  version: "1.0.0"
  description: |
    This is a REST API application developed with Express.

    ## Recommendations:
    - Ensure that all API requests include the necessary `authentication headers` if required.
    - Use the `Try it out` feature in Swagger UI to interact with the API and test different request parameters.

  # contact:
  #   name: "Devrabbit- Safe_wrapper"
  #   url: "https://lhswweb.dev.devrabbit.co/login"


servers:
  - url: "https://lhswapi.dev.devrabbit.co"
    description: "Pre Production Server"

  - url: "http://localhost:8201"
    description: "Local Server"

  #-----------------------------------------------------------------------------------------------------------------------------------

components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT

  #-----------------------------------------------------------------------------------------------------------------------------------
  schemas: # This should be properly indented
    User: # The User schema should be correctly nested under schem
      type: object
      properties:
        userId:
          type: string
          format: uuid
          description: "Unique identifier for the user."
          nullable: true
        accountId:
          type: string
          format: uuid
          description: "Reference to the account the user belongs to."
          nullable: true
        name:
          type: string
          description: "Full name of the user."
          example: "Devrabbit client"
          default: ""
        password:
          type: string
          description: "Hashed password of the user."
          default: ""
        role:
          type: string
          enum: ["super-admin", "admin", "manager", "support"]
          description: "Role assigned to the user."
          default: "admin"
        phone:
          type: string
          description: "User's phone number."
          pattern: "^[0-9]+$"
          minLength: 10
          maxLength: 15
          example: "0000000000"
          default: ""
          unique: [true, "Phone number has to be unique"]
        email:
          type: string
          format: email
          description: "User's email address."
          example: "nine123@devrabbit.com"
          default: ""
          unique: [true, "Email has to be unique"]
        status:
          type: string
          enum: ["active", "deleted", "blocked"]
          description: "Current status of the user."
          default: "active"
        createdBy:
          type: string
          format: uuid
          description: "Reference to the user who created this record."
          nullable: true
        updatedBy:
          type: string
          format: uuid
          description: "Reference to the user who last updated this record."
          nullable: true
        createdAt:
          type: string
          format: date-time
          description: "Timestamp when the user was created."
        updatedAt:
          type: string
          format: date-time
          description: "Timestamp when the user was last updated."
      required:
        - name
        - password
        - phone
        - email
        - password

    # Account:
    #   type: object
    #   properties:
    #     accountId:
    #       type: string
    #       format: uuid
    #       description: "Unique identifier for the account."
    #     accountName:
    #       type: string
    #       description: "Name of the account."
    #       required: true
    #     accountType:
    #       type: string
    #       enum: ["customer", "super-admin"]
    #       description: "Type of the account."
    #     companyName:
    #       type: string
    #       description: "Company name associated with the account."
    #     logo:
    #       type: string
    #       description: "URL of the company's logo."
    #     role:
    #       type: string
    #       description: "Role of the account, default is 'super-admin'."
    #     phone:
    #       type: string
    #       minLength: 10
    #       maxLength: 15
    #       pattern: "^[0-9]+$"
    #       description: "Mobile number of the account."
    #       unique: [true, "Phone number has to be unique"]
    #     email:
    #       type: string
    #       format: email
    #       description: "Email address of the account."
    #       unique: [true, "Email has to be unique"]
    #     password:
    #       type: string
    #       description: "Hashed password of the account."
    #     address:
    #       type: string
    #       description: "Address of the account holder."
    #     city:
    #       type: string
    #       description: "City of the account holder."
    #     state:
    #       type: string
    #       description: "State of the account holder."
    #     country:
    #       type: string
    #       description: "Country of the account holder."
    #     pincode:
    #       type: string
    #       description: "Pincode of the account holder."
    #     status:
    #       type: string
    #       enum: ["active", "in-progress", "deleted", "blocked"]
    #       description: "Status of the account."
    #     createdAt:
    #       type: string
    #       format: date-time
    #       description: "Timestamp when the account was created."
    #     updatedAt:
    #       type: string
    #       format: date-time
    #       description: "Timestamp when the account was last updated."
    #   required:
    #     - accountName
    #     - accountType
    #     - companyName
    #     - phone
    #     - email
    #     - password
    #     - city
    #     - state
    #     - country
    #     - pincode

    # WebhookMasters:
    #   type: object
    #   properties:
    #    webhookMasterId:
    #     type: string
    #     format: uuid
    #     example: "60d5ec49c3b2a72e4c8b4567"
    #    accountId:
    #     type: string
    #     format: uuid
    #     example: "60d5ec49c3b2a72e4c8b4568"
    #    userId:
    #     type: string
    #     format: uuid
    #     example: "60d5ec49c3b2a72e4c8b4569"
    #    location:
    #     type: string
    #     example: "New York"
    #    name:
    #     type: string
    #     example: "OrderWebhook"
    #    webHookUrl:
    #     type: string
    #     format: uri
    #     example: "https://api.example.com/webhook"
    #    authenticationCode:
    #     type: string
    #     unique: true
    #     example: "auth-123456"
    #    requestObject:
    #     type: object
    #     example: { "event": "order_created", "data": { "orderId": "12345" } }
    #    primaryHookId:
    #     type: string
    #     example: "primary-001"
    #    comments:
    #     type: string
    #     example: "Webhook for order processing"
    #    status:
    #     type: string
    #     enum:
    #     - active
    #     - offline
    #     - deleted
    #     example: "active"
    #    lastPullDate:
    #     type: string
    #     format: date-time
    #     example: "2024-07-23T10:30:00Z"
    #    webhookSettings:
    #     type: object
    #     properties:
    #      periodType:
    #       type: string
    #       enum:
    #         - each second
    #         - once each minute
    #         - once each hour
    #         - once each day
    #         - once each month
    #       example: "once each day"
    #      currentStatus:
    #       type: string
    #       enum:
    #         - start
    #         - stop
    #       example: "stop"
    #      interval:
    #       type: integer
    #       example: 1
    #      expiresOn:
    #       type: string
    #       format: date-time
    #       example: "2025-01-01T00:00:00Z"
    #   required:
    #    - accountId
    #    - name
    #    - webHookUrl
    #    - authenticationCode
    #    - webhookSettings

#-----------------------------------------------------------------------------------------------------------------------------------

paths:
  /api/users/user-login:
    post:
      tags:
        - Authorize
      summary: "1. Copy access_token from response || 2. Click Authorize button   ||  3. Place access_token in input box to authorize."
      description: |
        - Copy `access_token` from response  
        - Click the **Authorize** button  
        - Place `access_token` in the input box to authorize.
        - Set `desired expiration time` for a session in days only.  
          Examples:  
          default is set to `1 day  (1d)`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobileEmail:
                  type: string
                  description: "User's mobile number or email"
                  example: "0000000000"
                password:
                  type: string
                  format: password
                  description: "User's password"
                  example: "0000000001"
                sessionExpirationTime:
                  type: string
                  description: "Set desired expiration time for a session in either seconds, minutes ,hours,days, weeks, or years. Example: For minutes- 5m; For hours- 5h; For days - 5d; For Weeks- 5w; For Years- 5y"
                  example: "1d"
      responses:
       200:
        description: "Successful login response"
        content:
          application/json:
            example:
              status: "success"
              message: "Login successfull."
              data:
                access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RkNTg2ZTZkNjJmYjhkN2FlMWU5NTIiLCJpYXQiOjE3NDQxNzMwNDcsImV4cCI6MTc0NDE3NjY0N30.jQe7XNYuDSkwB3HQNjO2tGfkmyd0aHFO6nMMzj-Mjcc"
               
     
      security: [] # No authentication required for login
    
            

  #-----------------------------------------------------------------------------------------------------------------------------------

  # /api/webhook/get-webhook-payload-headers/{accountId}:
  #   get:
  #     tags:
  #       - API calls
  #     summary: "Get details of serial numbers of machines registered under an account and transaction types of received transactions."
  #     description: |
  #       - This API provides a list of serial numbers of machines registered under a specific `accountId`.  
  #       - Additionally, it retrieves all transaction types associated with these machines that have been recorded through webhooks.
  #       - Requires authentication via the `Authorization` header.
  #     security:
  #       - Authorization: [] # Requires Authorization header with token
  #     parameters:
  #       - name: accountId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #         description: "Unique identifier of the account for which webhooks are registered"
  #     responses:
  #       '200':
  #         description: Webhook payload headers.
  #         content:
  #           application/json:
  #             example:
  #               status: "success"
  #               message: "Webhook payload headers."
  #               data:
  #                 webhookPayloadHeadersData:
  #                   serialNumbers:
  #                     - "QA00579"
  #                     - "QA00577"
  #                     - "PA00581"
  #                     - "QA00578"
  #                     - "QA00580"
  #                   transactionTypes:
  #                     - "CashIn"
  #                     - "DoorOpened"
  #                 listOfWebhooks:
  #                   - webhookSettings:
  #                       periodType: "once each minute"
  #                       currentStatus: "stop"
  #                       interval: 10
  #                       expiresOn: "2025-04-01T06:15:44.625Z"
  #                     webhookMasterId: null
  #                     _id: "67eb8490233046c701342349"
  #                     webHookMasterId: "67eb8490233046c701342349"
  #                     accountId: "67eb81cb45715d3e5b678ebb"
  #                     userId: "67eb81cb45715d3e5b678ebd"
  #                     location: "India"
  #                     name: "Create work orders"
  #                     webHookUrl: "https://api.dev.isyncrabbit.com/api/webhook/81794/67eb81cb45715d3e5b678ebb"
  #                     authenticationCode: "31be5e06b50406b668fe7e591cf4560380df23535a81289c88f2e4d93625860e2213766324664aa05b34245520c2dde88f9a419ad218fc156c62193bae74c77b086e43b88fe498385ba38ec1c78ec15e6b1ec9f9c5fe27c6d533df865f48c2bcbf20be2d689f65b27fae5ee8b64930878f47d2da2585c1e87306c07ba1844202c8a87f7531dfe5d2ff8d70e6fed8aad8abb154c418a139082724411c2e3d6f71ef5b00f3e0a5002a357808df3d124e2c09a0111acc5934e42c77004409553cb1"
  #                     primaryHookId: "SerialNumber"
  #                     comments: null
  #                     status: "active"
  #                     lastPullDate: "2025-04-07T04:45:49.450Z"
  #                     createdAt: "2025-04-01T06:15:44.643Z"
  #                     updatedAt: "2025-04-07T04:45:49.450Z"
  #                     __v: 0    

  #-----------------------------------------------------------------------------------------------------------------------------------


  #-----------------------------------------------------------------------------------------------------------------------------------



  /api/machines/get-machine-transactions:
   get:
      tags:
        - API calls
      summary: "Retrieve statistical insights for an individual machine based on desired filters"
      description: |
        - This API provides detailed insights about a specific machine based on desired filters.  
        - By providing query parameters, users can retrieve denomination details, transaction summaries, and other key performance metrics.  
          The available query parameters are:  
          - `serialNumbers`: Filter by the machine's serial numbers.  
          - `transactionTypes`: Filter by the types of transaction `(e.g., CashIn, CashOut)`.  
          - `fromDate`: Retrieve records from this date onward.  `(e.g., 2025-04-21T10:40Z)`
          - `toDate`: Retrieve records up to this date.  `(e.g., 2025-04-28T10:40Z)`
        - Requires authentication via the `Authorization` header.
      security:
        - Authorization: [] # Requires Authorization header with token
      parameters:
      
        - name: serialNumbers
          in: query
          schema:
            type: string
          description: "Unique serial number identifying the machine."
       
        - name: transactionTypes
          in: query
          schema:
            type: string
          description: "Desired transaction types"
       
        - name: fromDate
          in: query
          schema:
            type: string
          description: "Desired date from which data to be retreived from.(e.g., 2025-04-21T19:09Z) "
       
        - name: toDate
          in: query
          schema:
            type: string
          description: "Desired date to which data to be retreived from. (e.g., 2025-04-28T20:09Z)" 
         
      responses:
        200:
          description: Successful response with machine report details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Reports of a single machine based on desired filters
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: "67eceef889c3a34af5486760"
                        # webhookMasterId:
                        #   type: string
                        #   example: "67eb8490233046c701342349"
                        # webhookMetaPayloadId:
                        #   type: string
                        #   example: "67eb8588233046c70134244c"
                        # accountId:
                        #   type: string
                        #   example: "67eb81cb45715d3e5b678ebb"
                        pickupGroupId:
                          type: integer
                          example: 566758091
                        serialNumber:
                          type: string
                          example: "QA00577"
                        retrievedOn:
                          type: string
                          format: date-time
                          example: "2025-03-27T17:33:05.4670000Z"
                        transactionDateTime:
                          type: string
                          example: "2025-03-27T09:57:05"
                        userName:
                          type: string
                          example: "TITAN"
                        transactionType:
                          type: string
                          example: "CashIn"
                        amount:
                          type: number
                          example: 10
                        denominations:
                          type: array
                          items:
                            type: object
                            properties:
                              UnitValue:
                                type: number
                                example: 5
                              Count:
                                type: integer
                                example: 2
                              Currency:
                                type: string
                                example: "USD"
                        location:
                          type: string
                          example: "Opal"
                        status:
                          type: string
                          example: "active"
                        createdAt:
                          type: string
                          format: date-time
                          example: "2025-04-02T18:02:00.120Z"
                        updatedAt:
                          type: string
                          format: date-time
                          example: "2025-04-02T08:02:00.120Z"
                        webhookTransactionId:
                          type: string
                          example: "67eceef889c3a34af5486760"
                        __v:
                          type: integer
                          example: 0
    